package com.togogotrain.moumoubicyclemanager.moumoubicyclemanager.entity;

public class Bicycle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bicycle.longitde
     *
     * @mbg.generated
     */
    private Double longitde;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.id
     *
     * @return the value of bicycle.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.id
     *
     * @param id the value for bicycle.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.mark
     *
     * @return the value of bicycle.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.mark
     *
     * @param mark the value for bicycle.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.status
     *
     * @return the value of bicycle.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.status
     *
     * @param status the value for bicycle.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.sign
     *
     * @return the value of bicycle.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.sign
     *
     * @param sign the value for bicycle.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.latitude
     *
     * @return the value of bicycle.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.latitude
     *
     * @param latitude the value for bicycle.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bicycle.longitde
     *
     * @return the value of bicycle.longitde
     *
     * @mbg.generated
     */
    public Double getLongitde() {
        return longitde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bicycle.longitde
     *
     * @param longitde the value for bicycle.longitde
     *
     * @mbg.generated
     */
    public void setLongitde(Double longitde) {
        this.longitde = longitde;
    }
}